from .nodes import NODE_CLASS_MAPPINGS as QQ_NODE_CLASS_MAPPINGS
from .number_to_string import NODE_CLASS_MAPPINGS as NUM_NODE_CLASS_MAPPINGS
from .text_scheduler import NODE_CLASS_MAPPINGS as TEXT_NODE_CLASS_MAPPINGS
from .text_scheduler import NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(QQ_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(NUM_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TEXT_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(TEXT_DISPLAY_MAPPINGS)

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
